### ISSUE TITLE
Enable tasks/checkboxes in Kanban

### ISSUE THREAD

**Issue by pwflint** [marcusolsson/obsidian-projects#101]
### What would you like to be added?

It would be nice to have tasks available for use in Kanban view. 

Clicking a task would give it a "Done" value. Unsure how this would affect the "status" field. In the demo project there are 3 values, so not T/F...

Additionally, the ability to drag and drop into different lists. 

Thanks!

PWF

### Why is this needed?

The utility of Kanban boards is to provide a heads up display for project status that can also be updated as dependency tasks are completed and the project can move into the next phase, or archived and clearing space for items in the backlog. 

Checking off tasks is one way to automate the archiving process. 

Drag drop is more intuitive for old dogs who used to work in boatyards and manage projects on physical Kanban boards and have not yet developed our "edit the data field" muscle.

PWF

**Comment by marcusolsson** [comment]
Do you have any examples of other products or services that use this pattern that can be used for inspiration?

Like you say, the user can have any number of columns, so a checkbox would need to know which column is the "Done" column. An alternative would be button that advances the card to next (right) column, whichever that may be.

Drag and drop is still a common pattern for these kinds of views, which I'm already planning to implement. I think a "click-to-advance" feature would need to complement that rather than replacing the drag and drop-paradigm.

I'm setting a low priority on this until it gains more traction (reactions and comments).

**Comment by dartungar** [comment]
@marcusolsson TickTick and its board view comes to mind, BUT for me it's also confusing (I have 'Done' column, what would I need checkboxes for?). However, it might be useful if columns are used to group notes other than by status (e.g by area of project).

side note: I've created an issue about drag&drop in board view before I saw your reply, so here it is anyway: https://github.com/marcusolsson/obsidian-projects/issues/133

**Comment by Acylation** [comment]
> However, it might be useful if columns are used to group notes other than by status (e.g by area of project).

Absolutely! Though I wonder if it's a "nonstandard" way to use kanban, it gives us more possibilities to show the same dataset from different aspects.

For example, I've create a folder/project, collecting all my assignments. They belongs to different **Subjects**, and have different **Types** like group works, presentations and exercises. I sometimes group them by these attributes, and the status is less important. Is this situation, a checkbox and a boolean field is enough. 

Another case is, when items in a project have different people in charge, we can group the items by each person. It helps assign tasks more efficiently. Also a checkbox will help.

Actually we have an option "check" in the calendar view, to mark the checkbox by a boolean field. It's very inspiring for this issue.
