### ISSUE TITLE
Dataview Project: Can not possible edit field using the table view

### ISSUE THREAD

**Issue by RTE90** [marcusolsson/obsidian-projects#143]
Hi, 
I set a Dataview project but i cannot edit the field. 

Thank you!

**Comment by marcusolsson** [comment]
Dataview projects are read-only. This is more of a technical limitation than a design decision, that most likely requires changes in the Dataview API.

**Comment by RTE90** [comment]
hello, the Task plugin should also make use of the Dataview API and the tasks can be edited. Couldn't you add the development of a similar functionality to the roadmap?

**Comment by marcusolsson** [comment]
Is this what you mean? https://obsidian-tasks-group.github.io/obsidian-tasks/other-plugins/dataview/

If so, they seem to add a `completion:: YYYY-MM-DD` attribute to the note. This works because they control the name of the attribute they want to edit (completion).

The problem for Projects is that a user could potentially alias fields and compute new fields that aren't part of the note.

For example, if the user created a project with the following query:

```
TABLE status AS "priority", priority AS "status" FROM "Work"
```

the query would only return the aliases in the result, which would lead to the wrong field being updated in this case.

I see two solutions to this:

- The Dataview API is updated to return the original field name, and whether a field is computed. I've been meaning to reach out to the Dataview team about this.
- The Projects plugin parses the query to create mappings between aliases and their original names. While this is possible, I don't want to reimplement the Dataview parser, which is going to be error-prone.

**Comment by marcusolsson** [comment]
I've created a feature request in the Dataview repository (https://github.com/blacksmithgu/obsidian-dataview/issues/1572).

**Comment by RTE90** [comment]
I understand the problems. :(

I refer to this https://obsidian-tasks-group.github.io/obsidian-tasks/getting-started/create-or-edit-task/ where also the description task is editable. But at first glance the problem about returned field name by dataview API remains.

**Comment by RTE90** [comment]
> I've created a feature request in the Dataview repository ([blacksmithgu/obsidian-dataview#1572](https://github.com/blacksmithgu/obsidian-dataview/issues/1572)).

Thank you!
