### ISSUE TITLE
Drag and drop cards in Board View without a Priority field

### ISSUE THREAD

**Issue by imeed166** [marcusolsson/obsidian-projects#205]
### What happened?

When switching "priority" to "none" in the board view, you can't drag the cards anymore.

### What did you expect to happen?

I expected DND to work regardless of the chosen priority.

### How can we reproduce it (as minimally and precisely as possible)?

https://user-images.githubusercontent.com/38974541/203784785-7d95108e-c545-4a07-8300-581246ab3d26.mov

### Plugin version

1.3.0

### Obsidian version

1.0.3

### OS

macOS

**Comment by marcusolsson** [comment]
Right now, views are designed to be stateless, using only data from the notes. To be able to sort cards without a priority field, the order needs to be stored in the plugin configuration. So the difference between using Prioritize field or not is where to store the order.

For now, you need to use a priority field to prioritize cards, so I'm changing this to a feature request.

**Comment by Acylation** [comment]
Maybe a hidden "default order" can be set to each file in the configuration. If user don't provide a priority field, the plugin can use the hidden order to sort card. When their is a sorting rule it will cover the hidden one.

The hidden order can be initialized by filename, or correspond to the row number of a file in table view. If modified in board view by drag-and-drop, the hidden order should keep updated.

**Comment by ltroj** [comment]
>To be able to sort cards without a priority field, the order needs to be stored in the plugin configuration.

That's a bit of a slippery slope. The way it is at the moment (stateless views) I can rely on my actions in the board view (and the other views) having a direct effect in the notes frontmatter (i.e. altering field values).

Introducing "hidden" configurations takes away some of that transparency.

**Comment by ryanjamurphy** [comment]
The issue is not just sorting priority, though. Without a priority field selected for a given board, you cannot drag and drop cards across statuses at all. 

This confused the heck out of me, hah. I spent about an hour debugging, as the demo project's board worked fine for dragging cards across status, but on my from-scratch board, I could only drag and drop entire columns.

A video reproducing the confusion, in case it's helpful:
https://share.cleanshot.com/5HWzxCVR

(I suggest renaming this issue to "Drag and drop cards in Board View without a Priority field".)

**Comment by imeed166** [comment]
This has been resolved, when the priority field was removed.

**Comment by Acylation** [comment]
Thanks for resolving this.
