### ISSUE TITLE
Provide a link or command to each project view

### ISSUE THREAD

**Issue by promethean** [marcusolsson/obsidian-projects#216]
### What would you like to be added?

A permanent link to each project, or a command to launch each individual project (like QuickAdd). 

### Why is this needed?

This plugin has great potential, and I respect the "leave no trace" philosophy but the limitation that it can only be launched via the ribbon or a command is deeply frustrating.   Other similar plugins (like DB Folder) do create a file that can be linked to from other resources.   This is far more usable, as you can search for it, link to it, and generally set it up in your workflow. 

If the 'leave no trace' philosophy stays and files are not an option - a workaround would be to provide a command for each project (rather than the default project).   We could then use this with Obsidian Advanced URI or otherwise to create our own links.  

Currently I can't see how to use this excellent plugin in my own workflows.  

Good luck !

**Comment by marcusolsson** [comment]
I don't see any problems with adding a command for projects, though I'm a little hesitant to add command for all projects by default. Instead, I imagine a switch in the project settings along the lines of "Add as command", "Create a command for this project". Would that work?

**Comment by axelson** [comment]
I'm not the originally poster but I have a similar request, and for me adding/enabling a per-view command via the settings would be great!

**Comment by marcusolsson** [comment]
Just to clarify, the command would be the same as "Projects: Show projects" command, with the difference that it selects a specific project?

I recently added the option to set a default project that will be opened first.

I'd like to know more about the use cases people have.

For example, are you frequently switching between two projects? If we had a command that shows the previously selected project, you could toggle between projects with a single command.

Or, is it the action of selecting a different project using the mouse? Would a command to cycle between projects work?

**Comment by axelson** [comment]
The option to set a default project isn't very useful for my workflow because I'm using two Projects (Projects and Books) roughly equally.

I currently have two projects with a few views in each:
- Projects (Project)
  - Table (View)
  - Board (View)
  - Database Folder (View)
- Books (Project)
  - Table (View)
  - Board (View)
  - Gallery (View)

So personally the two main commands I'd like to have are
- `Projects: Show Projects Table View`
- `Projects: Show Books Board View`

And I envision having more projects in the future so I'd like something more than just toggling between projects or views.

> Or, is it the action of selecting a different project using the mouse? Would a command to cycle between projects work?

Yes it is true that I really don't like having to use the mouse to make these types of changes.

**Comment by randomsnowflake** [comment]
Another +1 from me.

Being able to link projects would allow for adding a project view to the starred documents - which is what I want to do, but it is not possible right now.

**Comment by thecheesemo** [comment]
> I'd like to know more about the use cases people have.
> 
> For example, are you frequently switching between two projects? If we had a command that shows the previously selected project, you could toggle between projects with a single command.
> 
> Or, is it the action of selecting a different project using the mouse? Would a command to cycle between projects work?

I want to +1 this topic generally, but without the frustration. Your plugin does much of what I want, and it would only be made better with a command for each View in a Project 

I would specifically love the ability to have a command for each View in a Project that I've created. My use case is likely a bit different from the original intention of the plugin. As I use it "zooming out one level". In other words I have a project to manage my set of _Goals_, another to manage my set of _Projects_, another to manage my set of _Responsibilities(I call them Matters)_, and another to manage my set of _Tasks_. 

Those first three, my _Goals_, _Projects_, and _Matters_ track my overall commitments and responsibilities. The last one, _Tasks_ is centered around action Items generally. Each note in the _Tasks_ project contains a single obsidian task, using the [Tasks plugin](https://github.com/obsidian-tasks-group/obsidian-tasks). And, vice versa: each _Task_ in my vault is assigned to a single note. This way I can use plugins, like your Projects plugin, to help manage my time at the task level. 

However, **and there is where the commands for individual views becomes useful**, I also use other tools outside of your Projects plugin to manage these concepts. And, I have markdown note dashboards to quickly navigate between these other tools. Specifically speaking: 

- For my _Goals_, _Projects_, and _Matters_, I have several custom dataview list and table notes with dataview view toggles for quickly filtering and sorting those Items. 

- For my Tasks, I have the same as the others, but I also use the [Full Calendar plugin](https://github.com/davish/obsidian-full-calendar) to manage my scheduling and the [Obsidian Task Timeline](https://github.com/702573N/Obsidian-Tasks-Timeline) as a vault sidebar

- Finally, I have a quick _Navigation_ and _Creation_ sidebar that makes use of the [Advanced URI plugin](https://github.com/Vinzent03/obsidian-advanced-uri), that I use to quickly move around and create new notes. If Projects had a command for each View in a Project, I could add some of those to my sidebar. See the image below. I would like to replace the **Dashboard/Kanban** links with a command for specific View in a Project. Right now they link to outdated notes, that I no longer use because I discovered your plugin. 

![2023-02-21_6-17-45](https://user-images.githubusercontent.com/65478777/220331362-6d9ed62e-0209-43bf-ac13-6a8a6a5adaee.png)

thanks again for the work you've done. I can't do what you do, and what your done has helped me a lot already.

**Comment by HugoCastellanos** [comment]
+1 on this request. 

It is incredibly useful to be able to link to the default view of the default project via the Advanced URL plug-in [Show projects](obsidian://advanced-uri?commandid=obsidian-projects%253Ashow-projects)

I'd like to be able to link to the 3 different projects I plan on having. 1 for GTD Projects, 1 is a content calendar and another one is a CRM/UX Interview tracker. 

My workflow is mainly calendar-driven, so I regularly drop Obsidian links into the notes field of my calendar events. I'd block half a day with "Research for Podcast episodes" and add a link to my Content Calendar board so I can make progress on the pieces of content within it. 

It would be incredible to be able to link to specific views by right clicking into them. 

I am not sure how the syntax works, but Ideally something like: 

[Show projects](obsidian://advanced-uri?commandid=obsidian-projects%253Ashow-projects) // To show me the default project, this one works great already. 

[Review Kanban for Project A](obsidian://advanced-uri?commandid=obsidian-projects%253Ashow-projectA##Kanban) // To show me the Kanban for project A

[Process Status of Current Work Projects](obsidian://advanced-uri?commandid=obsidian-projects%253Ashow-projects-Work-Table) // Would show me all my work projects in the table view. 

Ideally I'd like to be able to grab these links pointing to the different views and use them in my calendar (Google Cal) or drop them as links within Obsidian for my Weekly Review Checklist. 

Currently I have to write reminders inside my Weekly / Daily Notes listing the project I have to review and which view to check, and it's not as elegant as a link would be. 

Thank you for all the great work you do. It's an incredibly useful plug-in.

**Comment by marcusolsson** [comment]
Here are some work-in-progress screenshots so far. I was initially thinking of mimicking the **Pinned commands** under the **Command palette** settings, but instead of dropdowns, I figured that the toggles makes for a less complicated UI. Let me know what you think!

I still have some work to do. The commands don't actually do anything right now.

<img width="798" alt="Screenshot 2023-03-18 at 10 58 21" src="https://user-images.githubusercontent.com/8396880/226098809-fc63ded9-0303-4378-abae-e3267a537897.png">
<img width="710" alt="Screenshot 2023-03-18 at 10 58 35" src="https://user-images.githubusercontent.com/8396880/226098810-c523e9b6-62c6-4444-ab3d-8031a42e98dd.png">

**Comment by whdmike** [comment]
> Here are some work-in-progress screenshots so far. I was initially thinking of mimicking the **Pinned commands** under the **Command palette** settings, but instead of dropdowns, I figured that the toggles makes for a less complicated UI. Let me know what you think!
> 
> I still have some work to do. The commands don't actually do anything right now.
> 
> <img alt="Screenshot 2023-03-18 at 10 58 21" width="798" src="https://user-images.githubusercontent.com/8396880/226098809-fc63ded9-0303-4378-abae-e3267a537897.png">
> 
> <img alt="Screenshot 2023-03-18 at 10 58 35" width="710" src="https://user-images.githubusercontent.com/8396880/226098810-c523e9b6-62c6-4444-ab3d-8031a42e98dd.png">


I have a situation. I mark my projects as shown above (under commends) but somehow they switch off (I have them around 20) when I close settings, and they are not shown inside command pallete.
