### ISSUE TITLE
Dataview query no longer works as project source

### ISSUE THREAD

**Issue by austingovella** [marcusolsson/obsidian-projects#222]
This dataview query stopped working:
TABLE Summary, Publisher, Last, Next, Date FROM "Writing/00 Drafts"

It generates this in the view:
<img width="799" alt="image" src="https://user-images.githubusercontent.com/539473/205443173-2019e47f-98b0-4465-b915-b599aaa29339.png">

This dataview query does work
TABLE FROM "Notes"

These are the field types as they appear in the Writing notes:
Summary:: Line of text
Publisher:: [[Link to Publication note]]
Last:: Line of text
Next:: Line of text
Date:: 2022-12-02

**Comment by MMoMM-org** [comment]
I have the same issue but I can't get it to work at all, not even with only a from statement.

TABLE Status AS Status from #type/resource/readwise

**Comment by austingovella** [comment]
And I got it working... I removed and re-added each part of the query and it started working when I re-added the FROM statement.

**Comment by MMoMM-org** [comment]
how, why... 😀 could you post your full query?

**Comment by marcusolsson** [comment]
I'm not able to reproduce this right now. I'll leave this open to see if others experience the same thing, or if you can provide a configuration that lets me reproduce the issue consistently.

**Comment by mbreiden** [comment]
```dataview
TABLE Status AS Status from #type/resource/readwise
```
which is working. Attached are the notes
[Archive.zip](https://github.com/marcusolsson/obsidian-projects/files/10168622/Archive.zip)

**Comment by austingovella** [comment]
It started working last week and stopped working this week.

Following @mbreiden's example, this query works in Dataview and returns nothing in Projects
`TABLE FROM #writing-status/draft`

I've also attached the notes where it is NOT working:
[01-Drafts.zip](https://github.com/marcusolsson/obsidian-projects/files/10202889/01-Drafts.zip)

**Comment by austingovella** [comment]
> which is working. Attached are the notes

I tried @mbreiden's notes in my vault along with the same query, and they did not work.

**Comment by austingovella** [comment]
I uninstalled, made sure the settings folder was deleted, and reinstalled and still have the same issue.

**Comment by AtlcatlQ** [comment]
same bug here

![image](https://user-images.githubusercontent.com/87624226/208279018-a4860522-9c66-412e-a1d8-b5c8f689eefc.png)

When I try to create a new note, it shows me this and doesn't allow me to created either:

![image](https://user-images.githubusercontent.com/87624226/208279030-31f70c6c-e0f4-4c6c-be93-963820aa8d4d.png)

But the same query works good in a Dataview table 

![image](https://user-images.githubusercontent.com/87624226/208279064-bf58ffbd-3d3b-41ed-a0d2-5991ce37b28d.png)

**Comment by wuzhen97** [comment]
the same

**Comment by Rhydderch** [comment]
I can confirm that dataview queries do not work. 
<img width="612" alt="image" src="https://user-images.githubusercontent.com/3197629/212479611-85491138-45fb-435a-9da3-1955f61d6d05.png">

<img width="397" alt="image" src="https://user-images.githubusercontent.com/3197629/212479605-000a02f1-9198-4cbf-82ec-ed07fd9c3f5b.png">

**Comment by marcusolsson** [comment]
Thank you all for chiming in on this. I'll be troubleshooting this during the coming week!

**Comment by marcusolsson** [comment]
I'm still unable to reproduce this on 1.11.1. I've tried the vaults and the various queries in this thread, and it yields the same results as the Dataview as far as I can see.

I first thought it was when you define a query without specifying any fields, i.e. `TABLE FROM "Notes"`, but I'm at least getting the `File` field with the note names.

Can someone confirm that this problem exists in the latest (1.11.1) version?

**Comment by Frigac** [comment]
I have the same issue happened using 1.11.5 Projects and 0.5.55 Dataview, both quite new version.

I tried a simple **dataview script** in normal note and it works well.
![image](https://user-images.githubusercontent.com/45989826/215962750-77675570-f902-45da-8ad2-a753db6d3cf4.png)
![image](https://user-images.githubusercontent.com/45989826/215962773-6c7d2a95-2d03-4f81-bb5d-bf91b5030300.png)

but when copy to **projects query**, it turns out **error**:
![image](https://user-images.githubusercontent.com/45989826/215962854-abf9bc07-2ed6-418c-94c1-f215ac055356.png)
![image](https://user-images.githubusercontent.com/45989826/215962905-ed7a237b-745d-4830-b931-55edcdb07864.png)

So I  have to use folder as source instead. It work well in other views, except the **database folder view** produces a totally **blank view**. Don't know whether it is because of the dataview in projects cannot work:
![image](https://user-images.githubusercontent.com/45989826/215963211-cc538239-e0c3-444b-bce9-be4858c36a8e.png)
BTW, the **DB folder plugin** work well in generate the db view, but I the multiview of projects are still things I want

**Comment by Radifire** [comment]
> So I have to use folder as source instead. It work well in other views, except the **database folder view** produces a totally **blank view**. Don't know whether it is because of the dataview in projects cannot work: ![image](https://user-images.githubusercontent.com/45989826/215963211-cc538239-e0c3-444b-bce9-be4858c36a8e.png) BTW, the **DB folder plugin** work well in generate the db view, but I the multiview of projects are still things I want

I had the same issue. Going into the settings for the DB folder, (in the projects view) then clicking out of it, renders the Database view for me.
