### ISSUE TITLE
Templater  plugin issue

### ISSUE THREAD

**Issue by ruanwz** [marcusolsson/obsidian-projects#246]
### What happened?

If I use <% tp.date.now('YYYY-MM-DD') %> in the template, there is an exception, makes the new note can't disappear in the note view list. I have to reopen the projects view.

```
plugin:obsidian-projects:55581 Uncaught (in promise) RangeError: Invalid time value
    at create_if_block25 (plugin:obsidian-projects:55581:40)
    at Object.p (plugin:obsidian-projects:55637:22)
    at update_slot_base (plugin:obsidian-projects:13542:10)
    at Object.p (plugin:obsidian-projects:54659:11)
    at Object.p (plugin:obsidian-projects:55012:45)
    at update (plugin:obsidian-projects:14019:32)
    at flush (plugin:obsidian-projects:13990:7)
```
There is a workaround, replace the following text
```
<% tp.date.now('YYYY-MM-DD') %> 
```

to
```
{{date}} 
```

Now there is no exception, I don't need to reopen the projects view.

### What did you expect to happen?

With the workaround, it is OK now.

### How can we reproduce it (as minimally and precisely as possible)?

use <% tp.date.now('YYYY-MM-DD') %> in the template

### Plugin version

1.4.0

### Obsidian version

1.1.6

### OS

macOS

**Comment by marcusolsson** [comment]
- I created a file Template.md, containing only `<% tp.date.now('YYYY-MM-DD') %>`.
- Added it as a template in the project settings.
- Created a new note from the template.

The note contains `<% tp.date.now('YYYY-MM-DD') %>` and I don't see any exceptions. Could you maybe give me the an exact template that generates the exception?

**Comment by ruanwz** [comment]
I have added a new note using the attached template, as you can see, there is an exception, and the new added note is showed as a blank item in the first row.  
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/4874/208678649-76312744-18c3-44b5-b130-eaba8d6c8502.png">

Then I need to close the view, and re-click the Projects sidebar icon to show it.
<img width="752" alt="image" src="https://user-images.githubusercontent.com/4874/208679386-bfcb742b-defe-4084-a9f1-ccac28575cdf.png">


[Project Note Template 1.md](https://github.com/marcusolsson/obsidian-projects/files/10268774/Project.Note.Template.1.md)

**Comment by marcusolsson** [comment]
I see that you're using the Templater string as a value for a date field. Projects doesn't support the Templater plugin yet, which means the template string won't be interpolated. 

I assume you have other files with the correct date format for `due`, causing Projects to detect the field as a Date field. When it encounters the Templater string, it's not able to parse it as a date, and fails.

Until we add support for Templater, this seems to be an expected behavior, though the plugin should probably display this as a parsing error in the cell rather than logging an exception.
