### ISSUE TITLE
Displaying Projects with different variables.

### ISSUE THREAD

**Issue by szfkamil** [marcusolsson/obsidian-projects#251]
### What would you like help with?

I have a folder with all my projects called "100. Projects". 

A project's front matter looks like this:

creation_date: 2022-12-20T17:20 
pro_deadline: 31-12-22
pro_start: 10-12-22
pro_end: 
type: project
status: #PRO/doing 
area: #project/workspace 

I tried using dataview, and it worked to display projects for a specific area, display all projects, all projects with a certain status, etc.—I think this plugin can do that better, right?

But my issue is that when I tried to display all projects from the "100. Projects" path, it displayed all notes inside all folders (since each project is its folder, not its note, right.) (I use folder notes, so each project also has a project note, which I wanted to display, but it still displays all the notes within all subfolders)

These are my settings for this view:
<img width="682" alt="Screenshot 2022-12-20 at 17 50 12" src="https://user-images.githubusercontent.com/82778513/208721371-2796889b-1ed7-4126-9b5c-d3accce2ab2a.png">

Did I grossly misunderstand the Projects plugin, or am I missing something? I mean, it's also called "Projects Plugin," right?? 

This is an example of what I used dataview for:
<img width="1478" alt="Screenshot 2022-12-20 at 17 51 41" src="https://user-images.githubusercontent.com/82778513/208721665-2e3f5846-bb05-4e68-a277-7e6086a9c5d8.png">

**Comment by marcusolsson** [comment]
Hi, and thanks for trying out the plugin! 

Each project defines a collection of notes to include in the project. Currently, you can use folders or Dataview queries to define what notes to include. 

The reason why it displays all notes under the folder you selected is because you have "Include subfolders" enabled, which will include notes from every subfolder.

If you have a folder per project in the 100. Projects folder, you may want to create separate Projects for each project folder.

**Comment by szfkamil** [comment]
It's not quite what I had in mind, tbh. I wanted to display all projects in one table with some data, but dataview can do that; this plugin could do it better (I thought). I don't need this now, but I'll keep it installed.

**Comment by marcusolsson** [comment]
I see! You'd like to see all the projects at once. Sounds similar to #140.
