### ISSUE TITLE
Select subfolder to add new note

### ISSUE THREAD

**Issue by JamesBarrettDev** [marcusolsson/obsidian-projects#314]
When a project is configured to include subfolders, it'd be useful to (optionally) select a subfolder when adding new notes to the project. Rather than all new notes being added to the root folder.

**Comment by marcusolsson** [comment]
Similar to #65 which is for Dataview projects. While this one is easier to implement, should probably sync the design between them.

Also, consider using the issue template for your next issue 🙏

**Comment by JamesBarrettDev** [comment]
Sorry, I didn’t see the templates. 

If GitHub asks you to login again when you click new issue, you get sent straight to a blank issue and the template selection doesn’t get shown. 😅

**Comment by marcusolsson** [comment]
That's weird! No worries though 👍

**Comment by marcusolsson** [comment]
#349 adds a new project setting "Location for new notes" where you can define the folder where to place new notes. Due to the limitations listed above however, for Dataview projects, you still can't create notes from within the views. But, you can use the **New** button or **Create new note** command to create notes.
