### ISSUE TITLE
Update table after "Hide fields" popup goes away

### ISSUE THREAD

**Issue by ggstrader** [marcusolsson/obsidian-projects#333]
### What happened?

With a table having 178 notes and 20+ fields, most of those fields aren't needed in the table. Right now, hiding a field refreshes the whole table which is slow. Toggling off many fields takes far too long.

### What did you expect to happen?

I should be able to toggle many fields, and the update should happen after the popup closes

### How can we reproduce it (as minimally and precisely as possible)?

generate a bunch of notes, with many fields, and random data in each field. Toggle multiple fields.

### Plugin version

1.10

### Obsidian version

1.1.9

### OS

Windows

**Comment by marcusolsson** [comment]
This is a broader technical limitation that applies to all the views at the moment. Basically, each of the views are recreated whenever their settings changes. I'm aware of the issue, and I agree it's frustrating. 

I need to do some more reading on Svelte's reactivity model to understand how to fix this. I had a go at it a while back but it turned into a mess that I had to revert.

**Comment by marcusolsson** [comment]
_(Did some debugging. This is mostly a note to my future self.)_

The data source is updated whenever the project definition changes:

https://github.com/marcusolsson/obsidian-projects/blob/4431061fa228c5efbe4948ef1de4253876713424/src/app/AppContainer.svelte#L34)

... which causes the plugin to perform a new query:

https://github.com/marcusolsson/obsidian-projects/blob/4431061fa228c5efbe4948ef1de4253876713424/src/app/AppContainer.svelte#L45

... which in turn removes the view while the query is running:

https://github.com/marcusolsson/obsidian-projects/blob/4431061fa228c5efbe4948ef1de4253876713424/src/app/AppContainer.svelte#L81

While the data source depends on the project definition, we don't need to run a new query whenever the data source changes.

For starters, we could change it so that the query only runs when the project id changes, or the [dataSource](https://github.com/marcusolsson/obsidian-projects/blob/4431061fa228c5efbe4948ef1de4253876713424/src/settings/v2/settings.ts#L18) changes. Changes to views shouldn't trigger new queries.

**Comment by marcusolsson** [comment]
This issue is the bane of my existence at the moment. It's a Svelte reactivity issue and after three separate rewrites, I haven't been able to figure this out. 

The plugin configuration right now looks something like this:

```js
const settings = {
  projects: [
    {
      id: "...",
      name: "...",
      views: [
        {
          id: "...",
          name: "...",
          config: {
            // ... 
          }
        }
      ]
    }
  ]
}
```

... which means that a change to the view config triggers a change to the project. And any changes to the project triggers a new query to run. Since queries may take a while, the view gets unmounted and replaced with a loading indicator. 

No changes to the view should result in a new query. 

I need to step away from this now. If any Svelte developers out there can help me figure this out, I'd be eternally grateful.

**Comment by ggstrader** [comment]
I can take a look later, but just from skimming it sounds like: if updating settings causes it, you can just not update them right? Save it in a temporary until the modal is destroyed then save it in settings

**Comment by marcusolsson** [comment]
If it helps, I tried to simplify the problem with two examples:

- https://svelte.dev/repl/a0dcc1df2ec347359ef8a4b9da102d8d?version=3.55.1
- https://svelte.dev/repl/7339fb0ae7854b03b1e1792cfcfcfc08?version=3.55.1

In the meantime, I'll see if I can start simplifying state management a bit. I'm definitely over-using stores which complicates things.

**Comment by marcusolsson** [comment]
I've pushed a [reactivity-issue](https://github.com/marcusolsson/obsidian-projects/tree/reactivity-issue/src/app/v2) branch with a simple playground to troubleshoot this.

I think if we can figure out a way to change the name of the view without running [this statement](https://github.com/marcusolsson/obsidian-projects/blob/48c2f5b87a64c1d4ea88da9a3bc5d5277bb272cf/src/app/v2/FrameProvider.svelte#L10), we should have a solution.

**Comment by ggstrader** [comment]
@marcusolsson I'm not really following. It looks to me that this issue is caused by this line:
https://github.com/marcusolsson/obsidian-projects/blob/4431061fa228c5efbe4948ef1de4253876713424/src/views/Board/BoardView.svelte#L146
If the config update is routed into the "onDestroy" method of the Switcher I believe that fixes the problem.
https://github.com/marcusolsson/obsidian-projects/blob/4431061fa228c5efbe4948ef1de4253876713424/src/views/Board/BoardView.svelte#L191

**Comment by marcusolsson** [comment]
Found a solution (finally! 🎉 ) to this, something I consider to be a "beautiful" hack.

By serializing the project definition for the data source into text, after having removed the views, Svelte can do a deep comparison of the project definition. Since the text representation of the project hasn't changed, it won't trigger an update.

https://github.com/marcusolsson/obsidian-projects/blob/c0b0fdc472e5c17b8d182ec200071ff5958bf6ef/src/app/DataFrameProvider.svelte#L16-L29

@ggstrader Thanks for looking into this! 🙏
