### ISSUE TITLE
Support non-Markdown files

### ISSUE THREAD

**Issue by mtgfyt1996** [marcusolsson/obsidian-projects#356]
### What would you like to be added?

forgive me if I somehow missed something but Projects don't seem to recognise canvas files yet? I don't need a preview or anything fancy, it just needs to show up with its name and path! thanks!

### Why is this needed?

canvases are used for many kinds of projects (e.g I am currently storyboarding)

**Comment by marcusolsson** [comment]
Projects only recognizes Markdown files at the moment, i.e. no images, videos, etc.

So rather than just .canvas files, this would require Projects to handle non-Markdown files. Using Markdown notes as records was one of the initial design decisions so changing this might require a significant amount of work.

**Comment by mtgfyt1996** [comment]
Thanks for that! I assumed this was the case, but since canvas is the first new native note format an exception might be possible. Can you suggest a workaround?

**Comment by marcusolsson** [comment]
Not that I can think of, unfortunately.
