### ISSUE TITLE
Display metadata

### ISSUE THREAD

**Issue by Rhydderch** [marcusolsson/obsidian-projects#53]
To improve the interoperability between the plugins and the ease of use, it would be great to be able to show metadata in the kanban cards. This is, for example, a column in one of the kanbans I use to manage projects.

<img width="233" alt="image" src="https://user-images.githubusercontent.com/3197629/194561668-304493e5-fec1-4e9b-82c5-a9f4e073abc1.png">
and this is the associated settings
<img width="369" alt="image" src="https://user-images.githubusercontent.com/3197629/194561778-6cb66085-ca44-4d4c-9b8b-0917c7851cf6.png">

**Comment by marcusolsson** [comment]
Very cool! Looks like the Kanban board plugin is solving this problem for you currently?

The Kanban plugin is superb and won't be able to (and don't want to) compete with it. In fact, my goal is that that (at some point) I'll be able to embed the existing Kanban plugin as a custom view.

The true goal of this plugin is to integrate existing plugins as views, while looking at the same data. You can read more here: https://github.com/marcusolsson/obsidian-projects/issues/27.

If it turns out that the above isn't feasible, I'm open to looking into this doing the road!

**Comment by seyeeL** [comment]
calendar view need too~

**Comment by marcusolsson** [comment]
@seyeeL What kind of information would you like to see in the calendar?

**Comment by seyeeL** [comment]
> @seyeeL What kind of information would you like to see in the calendar?

eg: I might select the journal folder and write something worth reviewing on the properties that I want to show on the calendar

**Comment by marcusolsson** [comment]
Current progress:

https://user-images.githubusercontent.com/8396880/212288596-6982790d-4112-4753-bef1-e54d42df37af.mov

**Comment by marcusolsson** [comment]
... and same idea for the Gallery view:

<img width="1440" alt="Screenshot 2023-01-13 at 10 53 45" src="https://user-images.githubusercontent.com/8396880/212290983-54f1b64d-fb04-4c28-a84e-b710861d1409.png">

I'll leave Calendar for now as I'm not sure it'll do as well considering the space constraints.

**Comment by Rhydderch** [comment]
Great progress. Thanks for working on this!
