### ISSUE TITLE
Filtered Views no longer work after most recent update

### ISSUE THREAD

**Issue by micwaab** [marcusolsson/obsidian-projects#537]
### What happened?

When using previously functioning filtered views, no filters are applied. This has not been an issue before, and I have used filters extensively with Projects.

### What did you expect to happen?

I expect to be able to select previously-created filters for projects, or create new filters and have my data reflect the filter criteria.

### How can we reproduce it (as minimally and precisely as possible)?

- Open a project
- Select a filtered view
- See that data is not filtered

_or_

- Open a project
- Create a new filtered view
- See that data is not filtered

### Anything else we need to know?

Thanks for your time!

### Plugin version

1.15.0 (currently installed: 1.15.0)

### Obsidian version

Current version: v1.2.5 (Installer version: v1.1.15) _updated to installer v1.1.16—no change in behavior_

### OS

macOS

**Comment by Acylation** [comment]
Sorry for the inconvenience caused by my careless mistake. I''ve just submit a fix to handle existing filters, hope it would work

Before the new version released, you may try to toggle the existing filters for several times, this would write the value of `enabled` field of it and the condition will up to work. Or you can just rollback to the previous version of the plugin.
