### ISSUE TITLE
Rename Views

### ISSUE THREAD

**Issue by As-Design18** [marcusolsson/obsidian-projects#572]
### What would you like to be added?

Its a small thing but i would like to see that you can rename your views after you created them :) 

### Why is this needed?

Because sometimes i create a view and name it somehow but as i go along i find myself using it for one purpose and then i want to rename the view but i cant so i have to create a new one with the same propaties :)

**Comment by Acylation** [comment]
You can rename the view by double clicking the view tab bar, and remember to press `enter` rather than clicking outside to accept the change.

![image](https://github.com/marcusolsson/obsidian-projects/assets/73122375/efd6e317-e42c-46fb-978d-ad2d86244daf)

I would like to support clicking outside as another way to accept the change.
