### ISSUE TITLE
Usability request: Move add note button up

### ISSUE THREAD

**Issue by jorgeherrera1** [marcusolsson/obsidian-projects#578]
### What would you like to be added?

When working on projects with many notes (+30), user has to scroll to the bottom every time they need to add a new note from the Projects View.  It'd be a nice usability enhancement that the Add note button is always visible at the top.

### Why is this needed?

It is not really needed per se, but it'd be a nice UX enhancement

**Comment by Acylation** [comment]
#408 FYI

**Comment by jorgeherrera1** [comment]
My apologies... I did try to find an item that is related but I guess I did not look well enough :(

I see the trail dates back to Jan and have read the conversation.  I still think this is a usability improvement that would be very well received. 

Should I close this out?  This is the first time I log something on github so not sure of the etiquette or process

**Comment by Acylation** [comment]
> I see the trail dates back to Jan and have read the conversation. I still think this is a usability improvement that would be very well received.

I agree. Since we have removed the ‘New’ button on the top-right corner, the suggestion would enhance the user experience. I’ve made some designs in thread #408 and your opinion is welcome.

> Should I close this out? This is the first time I log something on github so not sure of the etiquette or process

Generally, we should avoid duplicate issues and you can vote for existing feature requests. Here’s a more detailed guide for [contributing](https://github.com/marcusolsson/obsidian-projects/blob/main/CONTRIBUTING.md) in this repo. Thank you for your feedback on the plugin. You can safely close this and make further replies back in #408, as duplicate issues will be marked and closed by the owner during triaging.

**Comment by jorgeherrera1** [comment]
thanks @Acylation!! appreciate your prompt response.  I will continue contributing on #408
