### ISSUE TITLE
Priority is broken as of last release

### ISSUE THREAD

**Issue by ScottKillen** [marcusolsson/obsidian-projects#586]
### What happened?

The priority field no longer works and no longer appears in the settings  a project

### What did you expect to happen?

I expected things to work they way they always have

### How can we reproduce it (as minimally and precisely as possible)?

Try to set a priority field on a project. You can't

### Plugin version

1.16.0

### Obsidian version

1.3.5

### OS

Windows

**Comment by marcusolsson** [comment]
This is a breaking change. You can read more here: https://github.com/marcusolsson/obsidian-projects/pull/584

**Comment by ScottKillen** [comment]
Ahh. I know this was hard.

I really liked that the plugin automagically changed the priority when I dragged projects into a different order. It was one of the things that pushed this plugin above Kanban in my mind...

I will have to change my workflow a bit (😬), but I really love this plugin, and I appreciate your efforts. (I also know you make this available out of the goodness of your heart, and I am grateful. (❤️😀))

**Comment by ScottKillen** [comment]
.

**Comment by ScottKillen** [comment]
.

**Comment by marcusolsson** [comment]
I totally understand. 

UX-wise, the Board view has been the trickiest since I launched the plugin, and I hope that simplifying it will make it easier to maintain down the road. 

Ultimately, it's not my intention to innovate on individual views, but to provide a smooth integration between them.

I truly appreciate you being understanding ❤️ Once you've had a chance to adjust your workflow, I'd love to hear how you think we can build on this 🙏

**Comment by ScottKillen** [comment]
@marcusolsson Thank you. I will certainly participate more with feedback.

A few observations about the state of the plugin now:

1. You can still drag items into a different order within columns. This used to change the priority and was helpful; however, now, when you drag items into a different order, the plugin just resorts them. This can be confusing and maybe a way to further simplify. (TLDR: Do we need the ability to drag within a column if it doesn't do anything?
2. Unless you add a color (or include the priority field), there is no way to know if an item has the same priority as another item--before the plugin managed priority such that no item had the same priority as another.
3. With the above, styling has become more important, but three things make this difficult:
    1. The plugin does not expose data such as priority in the emitted HTML (like the tasks plugin does, for example)
    2. The plugin only exposed svelte classes.
    3. The color styling is emitted as a style attribute in the HTML, rather than kept in a separate CSS the way many other plugins provide.
4. If the style information were in a separate CSS, plugins like Style Settings could be very easily integrated (in fact, you might even be able to simplify the color styling by requiring Style Settings--which is already required by many mainstream themes)
5. The plugins ability to edit metadata of notes in the project is not well documented--but it is now needed to edit priority.
6. If you were to add a file context menu so that the plugin could edit the meta data of any note, it would eliminate the need for another plugin I use (MetaEdit) that cannot be used within the project view and unify the interface (Or likewise if you would add the file context menu to notes within the project, I could use that plugin to edit meta data within a project.

I hope that some of this is useful--of course, all of this is my opinion from my point of view and thus I understand it may not apply to your vision of the plugin.

I came to Projects from Kanban because, while Kanban is easier to style, IMO Projects is better precisely because it edits the metadata based on dragging into a new column.

I hope at least some of this is valuable.

**Comment by marcusolsson** [comment]
This is fantastic feedback! 🙏 

1. I agree that it's a bit confusing since it seems like you could reorder them. I'll see if I can sort the cards while you're still dragging. Though it might be confusing to have the cards "pop" away from the cursor. Will experiment.
2. Will have to think about this one.
3. This is a bigger effort that I've delayed a bit since it would require me to commit to style names to avoid messing up people CSS snippets. Though the layout and design has been stable for a while now, so maybe it's time to revisit this.
4. See 3.
5. What is it that you feel isn't documented? Ideally, I'd like to focus on making the UI as self-explaining as possible, before resorting to writing documentation for it.
6. This sounds interesting. Would you care to create a separate feature request for this, and maybe share some more details (I haven't used MetaEdit myself).

Actually, you gave me an idea that would let us reintroduce it in a possibly more understandable way that would cater to both regular and advanced users:

If the user hasn't configured any sorting criteria, the plugin would store the card order in the plugin configuration by default. Then we could introduce a setting called something like "Sync card order with field" that would instead use a field to determine order.

While the effect would be the same, from a UX perspective it's a simpler design that wouldn't clash with sorting. WDYT?

**Comment by ScottKillen** [comment]
Fantastic!

I used to be a software developer decades ago and am willing to test any of these for you.

As far as documentation--I think I discovered by accident that I could click on a note in the project, and the metadata edit dialog appears rather than opening the note. I could not find this in the docs, and this feature is even more important now that priority isn't adjusted automatically. (It eased life a bit to discover this.)

Ah, I see the complexity because **_any_** field could be the priority. Perhaps mandate that priority must be numeric? (This is difficult.)

I know you want to avoid storing anything in the project config--not meta is definitely better.

I use a product now where a list is sorted by default. If I drag and drop, sorting is suspended in preference to my dragged order. I have to choose a 'resort' command, which throws away my ordering and resort according to sorting rules.

I will add the feature request.

**Comment by axelson** [comment]
@ScottKillen have you opened a feature request for this new behavior yet? I'm not finding one in the issues.

I'd also like to have a way to use drag-and-drop to manually reorder notes in the board view, that's the main reason I use this plugin.

**Comment by ScottKillen** [comment]
@axelson it is #587

**Comment by ScottKillen** [comment]
@axelson  I've been using the KanBan plugin in conjunction with the Metadata plugin (set and configure the Kanban Board helper() to automatically change the status when I drag notes between lanes.

**Comment by pdfrod** [comment]
Is there any news on the possibility to use drag-and-drop to reorder cards? Having worked with other kanban platforms before, I found it quite confusing that this doesn't work. I spent some time trying to find if there was something missing in my configuration :sweat_smile: 

I was looking into migrating from the Kanban plugin, but not being able to easily re-order cards is quite a deal breaker for me. Anyway I can help push that forward?

**Comment by Stefan-59** [comment]
I just recently moved from the Kanban plugin (where I can easily reorder the cards in the columns, the result is stored in a markdown-file I can even edit, if I wich so) to this projects plugin, because I love the different views (table, board, calendar) on the same data.
But today I realized that it's not possible to reorder the cards in a column. This is close to a show-stopper for me, because I need to organize my work by using the order of the cards in my 'next action' column.

I'd be willing to add a 'priority' field, if that would help as a workaround (I see such field is mentioned quite often).

Question: how would I have to set up and use a priority field to be able to reorder the cards in any column?

**Comment by pdfrod** [comment]
> Question: how would I have to set up and use a priority field to be able to reorder the cards in any column?

You can't anymore; that's what this issue is about. That possibility was removed in https://github.com/marcusolsson/obsidian-projects/pull/584.

The best you can have at the moment is to configure a sort criterium based on an integer field (e.g., `priority`). This will allow you to see the cards sorted by priority, but you still can't drag & drop the cards; you have to manually update the integers value of every card in the list if you want to reorder them.

**Comment by Stefan-59** [comment]
Unfortunately, then this IS a show-stopper (at least for this specific use case) 🤷
Being able to have a nice visual overview over all items WITH there sort-order and being able to adjust it easily is exactly the motivation to use the Kanban-view in this case.
So, I will go back to the Kanban Plugin until there might be a solution with Projects, which will let me happily come back (I very much appreciate the other additional features I'm missing with the Kanban Plugin).

For the time being I will use Projects for another use-case, so I will stay up to date with the ongoing development.

Thank you anyway for having made this great plugin and your support!! 🙏

**Comment by Acylation** [comment]
@Stefan-59 thanks for tracking this and your patience. I noticed #706 in discussions, sorry for the inconvenience. I just got time to handle messages, and will still have a tight schedule until early December. I'll start a PR and link back here when I start working on this.

**Comment by adsilcott** [comment]
I had a thought about this, I hope you don't mind me sharing it here. 

One of the things that I love about the Kanban plugin is that if you look at the text version it's just a simple markdown file. The plugin is just changing how it's displayed and updating the original file when the Kanban view is changed. I think this is what we all want from Obsidian, that if a plugin went away we could look at our data and it would still make sense.

What if the Board view created a file that was just that, a Markdown file in the Kanban format, except instead of holding the data in its hierarchy it would hold links to the data, since in this board the tasks are all separate notes. The beauty of this is that not only would it store the user's preferred ordering without adding any metadata to the files, but it would create a useful markdown file that could be embedded elsewhere or even loaded into other plugins.

**Comment by ScottKillen** [comment]
@adsilcott This is an excellent suggestion--however, doing so would make this plugin just a limited version of Kanban, as a Kanban board can contain tasks that are links to other tasks. Paired with the Meta-Bind plugin, Kanban can change linked notes' 'status' property when tasks are dragged from one lane to the next.
FWIW, I no longer use this plugin precisely because it is unnecessarily proprietary and limiting. The feature I loved most about it,  priority management, was removed in the last release. This is the author's right, and I don't begrudge him that--however, it forced me to adapt Kanban to my needs, and I won't look back.

**Comment by st4ng** [comment]
@Acylation  Have you started working on this? If not I might submit a PR.

**Comment by Acylation** [comment]
@st4ng so nice to hear about this! There's no in-progress work on this so please feel free to submit one. Thanks for your interest in contributing to Projects.

**Comment by Acylation** [comment]
Mark as complete by #788
