### ISSUE TITLE
FR - clicking on items in Kanban board, should open the page. or atleast have a setting for it

### ISSUE THREAD

**Issue by brappier** [marcusolsson/obsidian-projects#598]
### What would you like to be added?

 clicking on items in Kanban board, should open the page. or atleast have a setting for it

### Why is this needed?

good UX

**Comment by marcusolsson** [comment]
If you press Shift and click the link, it'll open the note instead of editing it. Is that what you're looking for?

**Comment by brappier** [comment]
Yes, that works, 
i'm not sure what should be the default behavior if you do normal click. 
In notion normal click just opens the page

**Comment by jaredoOS** [comment]
It works in table view - and as default for me - but not in Kanban view. I'd LOVE it in Kanban view.

**Comment by marcusolsson** [comment]
Sorry, it should be Ctrl (or Cmd) instead of Shift. My bad.

**Comment by jaredoOS** [comment]
Thanks. I swear I tried that last night and it didn't work... but it is this morning, thanks.

**Comment by marcusolsson** [comment]
> i'm not sure what should be the default behavior if you do normal click.

My reasoning is that when you're in Projects, you're planning and managing content. The default action should reflect that.

Making things configurable is always an option, but I'd prefer to solve things by improving the UX rather than defaulting to configuration options.

Regardless of which action is default, it should be easy to discover the other action. For example, would a tooltip that says something like "Press Ctrl and click to open note"?

**Comment by gloryVine** [comment]
I just wanted to mention that I'm a new user and almost uninstalled the plugin again because of this behavior. I'm used to just having to click on a link in Obsidian to get to the corresponding note, and this being not the default behavior in the Kanban board causes enough friction / cognitive overhead for me almost not wanting to use the plugin. I know this sounds pretty drastic but it's small things like this that makes me choose one tool over the other when I'll have to use it everyday.
I'd really appreciate if you could reopen this issue and hopefully consider implementing this as a setting in the future.
Thanks a lot for the plugin.

**Comment by Acylation** [comment]
Mark this as resolved by #620
