### ISSUE TITLE
Select first day of week in Calendar view

### ISSUE THREAD

**Issue by Dakforever** [marcusolsson/obsidian-projects#665]
### What would you like to be added?

Is there a way to change the first day of week in calendar view, I've been through the GitHub community section and the bug reports but have not found a way to change it, 

### Why is this needed?

Sunday has always been the first day of the week on every calendar I have ever owned and it's a bit jarring to use Monday instead.

Thanks in advance, your plugin is the reason I'm staying with Obsidian.

**Comment by Acylation** [comment]
I will close this since there's already an issue tracking the feature, thanks for posting the request anyway. Many users are looking forward to configure the starting day of a week,  and I'm considering promoting this. While I wish I could guarantee its implementation, unfortunately, due to limitations in my development skill and the need to fix some bugs before adding new features, I cannot make any promises at this time.

In addtion, you can show your support for existing feature requests by using the 👍 reaction to help priorize the feature. If you have any other questions or concerns, please don’t hesitate to let me know. Thank you! 😊
