### ISSUE TITLE
Markdown code doesn't render in Kanban titles and Table column options

### ISSUE THREAD

**Issue by Hexara7777** [marcusolsson/obsidian-projects#666]
### What happened?

When I create a kanban view and set the titles of the columns to be a certain property, and I have set those titles with the double * for bold for example, it doesn't render bold but instead shows as:
`**text**`
![image](https://github.com/marcusolsson/obsidian-projects/assets/130001839/928d759f-de02-454c-b7d8-6205af2c39d6)
![image](https://github.com/marcusolsson/obsidian-projects/assets/130001839/791845ba-ce47-47a7-bf86-005456bb1144)

### What did you expect to happen?

To render markdown everywhere

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a project from a folder
2. Create a new property
3. Check allow markdown to render
4. Add an "option"/some value with markdown code like bold or color
5. The drop down menu for the options won't render markdown code in table view
6. Create kanban view and set it to group by the previously created property
7. Titles for column title won't render markdown code as well

### Anything else we need to know?

No

### Plugin version

1.16.3

### Obsidian version

1.4.5

### OS

Windows

**Comment by Acylation** [comment]
Thanks for sharing your usecase! I would consider this to be a feature request rather than a bug, as enabling rich text rendering is an optional feature initially introduced for the table cells in #319 .

Since the board column title is essentially also a field value, we can work on the proposal, but it will require some detailed design. For example, should we place the Enable rich text configuration in each view, or make it an option for the entire plugin? Also, how to let auto-complete ignore/render the rich text? 

For now, if you enable rich text formatting in the field configuration (which can only be found in the table view) and include this field in the board/gallery view, you will see the rich text taking effect. This is explained in #372 . It seems that we need to find a better way to manage fields and field configurations.

![image](https://github.com/marcusolsson/obsidian-projects/assets/73122375/8d4a7ffc-51a0-4e62-a095-45b4e4c6fbd3)

**Comment by Acylation** [comment]
This issue sound like #316 quite a bit.

**Comment by Acylation** [comment]
Part of this request is implemented in #732. While the request on rich-text rendering in auto-complete requires a upstream change, or we should build an auto-suggest by ourselves. So I would mark this as resolved and open up another issue to track changes on auto-suggest.
