### ISSUE TITLE
Sort number-prefixed notes in a natural order

### ISSUE THREAD

**Issue by RyotaUshio** [marcusolsson/obsidian-projects#671]
### What would you like to be added?

Hi, thank you so much for this great plugin!

When note titles are prefixed with numbers (e.g. chapter number in a textbook), sorting by name (A->Z) doesn't work as expected. For example, in the image below, chapter 10 comes right after chapter 1, and chapter 2 comes after chapter 17.

<img width="1552" alt="image" src="https://github.com/marcusolsson/obsidian-projects/assets/72342591/e58a78ab-a287-4841-bebc-88f359bdeef9">

I know this is the "right" behavior in a pure computer science sense, but it's counterintuitive as a UI in my opinion.

What I would like this plugin to be able to do is that, sorting notes prefixed with numbers in a "natural" order, just like the core File Explorer plugin does:

<img width="406" alt="image" src="https://github.com/marcusolsson/obsidian-projects/assets/72342591/e064fbaa-9181-4ea7-9438-7391dfc0bb86">

### Why is this needed?

This is needed because natural sorting will definitely improve the user experience by removing the counterintuitive part from the plugin. 

I can use "01", "02", ... instead of "1", "2", ... as a quick fix, but it makes the chapter numbers look differently from the original textbook, which I (and probably many others) don't want.

**Comment by Acylation** [comment]
Good idea! I'll check it out since this is a common use case, and we want the plugin to be consistent with the Obsidian main application. Not quite sure if we should make natural sort an option or the default behavior.

Will check `localeCompare()` usage in the plugin, and refer to https://stackoverflow.com/questions/2802341/natural-sort-of-alphanumerical-strings-in-javascript 

Thanks for proposing this!

**Comment by RyotaUshio** [comment]
Thank you for the quick response! I look forward to seeing this implemented.
