### ISSUE TITLE
multi select fields not showing in board view

### ISSUE THREAD

**Issue by BindingOx** [marcusolsson/obsidian-projects#710]
### What would you like to be added?

If I have a multi select field like

```
status:
- To do
# - Doing  
# - Done
```

It shows correctly in Table view but not Board view. Chaning the property type to list or text or using quotes made no difference.

### Why is this needed?

True kanban board

**Comment by Acylation** [comment]
I just tested this and the problem is reproducible. Removing the hashes would help, but if you want to ignore some values in your use case, than the `hash` comment would be neccessary. I'll look into it as the inconsistent behavior between views may cause further problems.

However, if you'd like you adjust your workflow, I would recommand the built-in support for predefined values by Projects. Through Table view you can set predefined values, and use them later for convenience. #661 FYI

**Comment by BindingOx** [comment]
Ok Thanks! Your solution of setting predefined values is just what I needed.

**Comment by Acylation** [comment]
So glad that it helps!
