### ISSUE TITLE
Filter support for all views

### ISSUE THREAD

**Issue by imeed166** [marcusolsson/obsidian-projects#80]
For now, there are no benefits in creating many table views, except for different sorting and hiding preferences. To add real value, in my opinion, we need to have different filters in each table view.

I was wondering if it's in your plans to add support for filters in the table view.

Edit: Actually, this is all related to this issue https://github.com/RafaelGB/obsidian-db-folder/issues/574, and I was wondering about which plugin will handle filtering if they work together. So I thought that If DB folder will not handle filtering anymore when embedded in this plugin (because of conflicts) then I should create a feature request to address this issue.

**Comment by marcusolsson** [comment]
Great suggestion! 

I've had this idea to filter before the data is actually sent to each view. That way, views wouldn't need to bother with filtering themselves, and it would automatically work for all views. I'd need to do some testing, but shouldn't require too much work.

**Comment by marcusolsson** [comment]
I did a prototype on this, inspired by how GitHub Projects work, where you could type a query like: `status:Done work` to search for all notes with status set to Done, and that contains "work". 

This looks like the native Obsidian search syntax, which could be confusing. Especially since I plan on adding a third data source that accepts a Obsidian search term. Since the Obsidian native search has reserved keywords like `path:...` or `tags:...`, it would likely be confusing to use two similar but different query strings.

I'm leaning towards building a more intelligent UI that lets you select a field, and then the filter operation. For example, for number fields you could use a "greater than" filter operation, which wouldn't be available for boolean fields etc.

Of course, this means that we'd need to find a good place for a UI like this. I worry that the toolbar might get a bit cluttered with more settings being added. We could add a modal for setting up filters, but I think it would be better if you could immediately see the filters being applied, so I'm experimenting with a new collapsing sidebar instead.

Stay tuned!

**Comment by marcusolsson** [comment]
I'm liking this design so far. I'm not sure how it'll translate into mobile, though I assume Obsidian handles popovers. 

<img width="1015" alt="CleanShot 2022-12-19 at 00 06 38@2x" src="https://user-images.githubusercontent.com/8396880/208324139-9305b721-16ed-4465-911e-668f5cb6a5ea.png">

What types of comparisons would be most important to you? It most likely won't have a complete set of comparisons in the first version.

**Comment by marcusolsson** [comment]
https://user-images.githubusercontent.com/8396880/208426709-90946b8c-88e4-4d88-b369-253dbaea1838.mp4
