### ISSUE TITLE
Calendar View does not work anymore on mobile/iPad

### ISSUE THREAD

**Issue by rtadewald** [marcusolsson/obsidian-projects#939]
### What happened?

Since the last update, the Calendar View doest not work anymore in my iPhone or iPad.
Here's a screenshot of the blank screen I got now:

<img src="https://github.com/user-attachments/assets/f4463063-7e73-4fd6-a593-53fdc4f082a0" width="300"/>

### What did you expect to happen?

Render it like in my MacOS.

![image](https://github.com/user-attachments/assets/6f654287-25a8-42e6-961b-1fc6d1a93f72)

### How can we reproduce it (as minimally and precisely as possible)?

Open the calendar view in a mobile device.

### Plugin version

1.17.4

### Obsidian version

1.6.7

### OS

macOS, Other

**Comment by Acylation** [comment]
Thanks! Should have taken a look at the mobile version. A rough investigation has narrowed this problem to no later than #887

**Comment by tjg23** [comment]
Has there been any more progress on this? I just ran into this issue as well (because I just tried to create a calendar view, not bc it had been working correctly). If it hasn't been found already, here's a screenshot of the error that is thrown when I try to open the calendar:
![IMG_0553](https://github.com/user-attachments/assets/8439bb87-9034-4643-afe8-c30143594d6f)

**Comment by Acylation** [comment]
Problem identified. Thank you so much @tjg23 for the key debug info. Introduced by #877, actually caused by different implementation on `Intl.Locale().weekInfo` by Node.js vs `Intl.Locale().getWeekInfo()`, a more standard version established by both Safari and Chromium. Quick fix coming up and hopefully this will lead to a minor version release.

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale/getWeekInfo
