### ISSUE TITLE
enhancing the sorting option of columns  for the date attributes

### ISSUE THREAD

**Issue by erfanbashar1q** [marcusolsson/obsidian-projects#94]
### What would you like to be added?

Hello

it will be great that we can sort the table by the sorting options like A to Z, that is already included; but it is not complete i think.
i think one of the most important and efficient type of sorting is sorting based on the increasing or decreasing date.
now if we have date attribute in the metadata of notes, the plugin can detect it, but the sorting option of this column is based on A to Z; it will be great to enhance this sorting option at least for data attribute to able to sorting the notes in the table form based on decreasing or increasing of date.

### Why is this needed?

it will be super helpful to see the notes in the table based on the  decreasing or increasing orientation of date that is inserted in the metadata of notes.

**Comment by marcusolsson** [comment]
I think this is a good first issue for anyone looking to contribute.

Here's a good starting point: https://github.com/marcusolsson/obsidian-projects/blob/f7e4bd0cf8e8ae28e81f7fe1e20221dfb222f2a5/src/views/Table/components/DataGrid/data-grid.ts#L48-L83

I imagine you'd need to use `isDate()` to determine whether to sort by date.

Bonus points if the [menu options](https://github.com/marcusolsson/obsidian-projects/blob/f7e4bd0cf8e8ae28e81f7fe1e20221dfb222f2a5/src/views/Table/components/DataGrid/DataGrid.svelte#L69-L80) said something like "New -> Old" instead of "A -> Z".

**Comment by GamerGirlandCo** [comment]
i'll bite!
